//CURSO DE PIC
//PROGRAMA 15 MULPLEXACAO DE LEDS COM PIC16F628A
//GUILHERME CARVALHO

//CONSTATNTES
#define LED1 RA0_bit
#define LED2 RA1_bit

void main() {
     //CONFIGURACOES
     CMCON = 0x07;//DESABILITA OS COMPARADORES
     TRISA = 0x00;//CONFIGURA O PORTA COMO SAIDA DIGITAL
     PORTA = 0x00;//INICIALIZA O PORTA COM NIVEL BAIXO
     
     while(1){//MULTIPLEXACAO DE LEDS EH FAZER COM QUE OS LEDS PISQUEM EM UMA FREQUECIA ALTA FAZENDO COM QUE APARENTEM QUE ESTAJAM SEMPRE LIGADOS
              LED1 = 0x01;
              LED2 = 0x00;
              delay_ms(100/50);//PERIODO = 1/FREQUENCIA
              LED1 = 0x00;
              LED2 = 0x01;
              delay_ms(100/50);//PERIDO = 1/FREQUENCIA
     }

}