//CURSO DE PIC
//PROGRAMA 21....TERMOMETRO QUE MOSTRA OS VALORES EM CELSIUS E EM FAHRENHEIT E MOSTRA OS VALORES NO TERMINAL USANDO UART COM O PIC16F877A
//MAIS INFORMAÇÕES NO LINK: https://www.youtube.com/watch?v=ilBr-iB6NgU&index=21&list=PLZ8dBTV2_5HQ-LrS9r1dP30h8n9sh04gh
//GUILHERME CARVALHO

//MAPEANDO O HARDWARE
#define S1 RB0_bit
#define S2 RB1_bit

//VARIAVEIS
char uart_rd;
long int valorAD = 0;
char txt[7];
//FUNÇÕES DECLARAÇÃO
void Celsius(long AD);
void Fahrenheit(long AD);
//INICIO DA MAIN
void main() {
     //CONFIGURANDO OS REGISTRADORES
     CMCON = 0x07;//DESABILITA OS COMPARADORES
     ADCON0 = 0x01;//HABILITA A CONVERÇAÕ A/D
     ADCON1 = 0x0E;//TORNA AN0 UMA ENTRADA ANALOGICA
     //INICIALIZANDO A COMUNICAÇÃO UART
     UART1_Init(9600);//INICIALIZA A COMUNICAÇÃO UART COM 9600 BPS
     Delay_ms(100);//DELAY PARA A ESTABILIZAÇÃO DA COMUNICAÇÃO UART
     UART1_Write_Text("START");//MENSAGEM QUE MOSTRA QUE A COMUNICAÇÃO ESTA FUNCIONANDO
     UART1_Write(10);//ESCREVE O ESPAÇO....10 = ESPAÇO NA TABELA ASCII
     UART1_Write(13);//QUEBRA LINHA....13 = QUEBRA LINHA NA TABELA ASCII
     //CONFIGURANDO O PORTB
     TRISB = 0x03;//DEFINE RB0 E RB1 COMO ENTRADAS DIGITAIS
     PORTB = 0x00;//INICIALIZA O PORTB COM NIVEL BAIXO
     //LOOP PRINCIPAL
     while(1){ 

               if (UART1_Data_Ready()) {     // If data is received, //********************PARTE TIRADA DO HELP
                                       uart_rd = UART1_Read();     // read the received data,
                                       UART1_Write(uart_rd);       // and send data via UART
               }//**********************PARTE TIRADA DO HELP
              if(S1 == 1 && S2 ==0){
              valorAD = ADC_Read(0);
              Celsius(valorAD);
              }
              if(S1 == 0 && S2 ==1){
              valorAD = ADC_Read(0);
              Fahrenheit(valorAD);
              }
              else{
                   UART1_Write_Text("AGUARDANDO");//MENSAGEM QUE MOSTRA QUE A COMUNICAÇÃO ESTA FUNCIONANDO
                   UART1_Write(10);//ESCREVE O ESPAÇO....10 = ESPAÇO NA TABELA ASCII
                   UART1_Write(13);//QUEBRA LINHA....13 = QUEBRA LINHA NA TABELA ASCII
                   Delay_ms(150);
                   }
              
     }
    //FIM DO LOOP
}
//FIM DA MAIN

//IMPLEMENTAÇÃO DAS FUNÇÕES

/*ESSA FUNÇÕA RECEBE O DADO DA ENTRADA ANALOGICA E CONVERTE ESSE NUMERO EM UM VALOR DE TEMPERATURA EM GRAUS CELSIUS...
 A CONVERSÃO EH FEITA COM BASE NO DATASHEET DO SENSOR LM35....ESSE SENSOR VAIRIA 10mV/C...FAZENDO A REGRA DE 3 PARA
 DETERMINAR A TEMPERATURA......Delay_us 1C -> 0,01V ASSIM COMO VALOR -> 5V, LOGO....VALOR*0,01/5.......DEPOIS DEVEMOS
 DIVIDIR O VABOR POR 1023 POIS O CONVERSOR A/D EH DE 10 BITS (2^10=1024...ZERO CONTA...ENTAO 1023)...DEPOIS ESSE VALOR
 É CONVERTIDO PARA UMA STRING E ESSA STRING É IMPRESSA NO TERMINAL
*/
void Celsius(long AD){
     long valor;//VARIÁVEL AXILIAR
     valor = AD*500/1023;///CONTA PARA A CONVERSÃO PARA CELSIUS
     IntToStr(valor , txt);//CONVERTE O LONG EM STRING
     UART1_Write_Text(txt);//IMPRIMI O VALOR DA MEDIÇÃO EM GRAUS CELSIUS
     UART1_Write_Text(" CELSIUS");//IMPRIMI A string
     UART1_Write(10);//IMPRIMI O ESPAÇO
     UART1_Write(13);//IMPRIMI O QUEBRA LINHA
     Delay_ms(150);//DELAY PARA VISUALIZAÇÃO
}

/*ESSA FUNÇÕA RECEBE O DADO DA ENTRADA ANALOGICA E CONVERTE ESSE NUMERO EM UM VALOR DE TEMPERATURA EM GRAUS FAHRENHEIT...
 A CONVERSÃO EH FEITA COM BASE NO DATASHEET DO SENSOR LM35....ESSE SENSOR VAIRIA 10mV/C...FAZENDO A REGRA DE 3 PARA
 DETERMINAR A TEMPERATURA......Delay_us 1C -> 0,01V ASSIM COMO VALOR -> 5V, LOGO....VALOR*0,01/5.......DEPOIS DEVEMOS
 DIVIDIR O VABOR POR 1023 POIS O CONVERSOR A/D EH DE 10 BITS (2^10=1024...ZERO CONTA...ENTAO 1023)...ESSA OPERAÇÃO 
 RETORNA O VALOR EM GRAUS CELSIUS...ESSE VALOR DEVE SER MULTIPLICADO POR 1,8 E SOMADO 32 PARA O AJUSTE DE ESCALA...
 DEPOIS ESSE VALOR É CONVERTIDO PARA UMA STRING E ESSA STRING É IMPRESSA NO TERMINAL
*/
void Fahrenheit(long AD){
     long valor;//VARIÁVEL AUXILIAR
     valor = AD*500/1023;//CONVERSÃO PARA CELCIUS
     valor = (valor*1.8)+32;//CONVERSÃO PARA FAHRENHEIT
     IntToStr(valor , txt);//CONVERTE INT PARA STRING
     UART1_Write_Text(txt);//IMPRIMI A STRING EM GRAUS FAHRENHEIT
     UART1_Write_Text(" FAHRENHEIT");//IMPRIMI A STRING
     UART1_Write(10);//IMPRIMIR O ESPAÇO
     UART1_Write(13);//IMPRIMI O QUEBRA LINHA
     delay_ms(150);//DELYA PARA VISUALIZAÇÃO
}